CREATE TABLE IF NOT EXISTS Thread
(
  threadID INTEGER AUTO_INCREMENT,
  authorID INTEGER NOT NULL,
  title VARCHAR(128),

  PRIMARY KEY (threadID),

  FOREIGN KEY (authorID) REFERENCES User(userID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Message
(
  messageID INTEGER AUTO_INCREMENT,
  threadID INTEGER NOT NULL,
  authorID INTEGER NOT NULL,
  title VARCHAR(128),
  content TEXT,

  PRIMARY KEY (messageID),

  FOREIGN KEY (threadID) REFERENCES Thread(threadID),
  FOREIGN KEY (authorID) REFERENCES User(userID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS User
(
  userID INTEGER AUTO_INCREMENT,
  name VARCHAR(64),
  password VARCHAR(256),

  PRIMARY KEY (userID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Tag
(
  tagID INTEGER AUTO_INCREMENT,
  label VARCHAR(128),

  PRIMARY KEY (tagID)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS MessageTags
(
  tagID INTEGER NOT NULL,
  messageID INTEGER NOT NULL,

  PRIMARY KEY (tagID, messageID),

  FOREIGN KEY (tagID) REFERENCES Tag(tagID),
  FOREIGN KEY (messageID) REFERENCES Message(messageID)
) ENGINE = INNODB;